spring.application.name=ICSec_App

# Database config
spring.datasource.url=jdbc:h2:file:./data/icsec
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=ChangeMe123
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasourcex-initialization=true
spring.jpa.hibernate.ddl-auto=update


# TODO: Remove in prod
spring.h2.console.enabled=true
spring.h2.console.path=/h2

server.port=8080
spring.web.error.whitelabel.enabled=false
spring.web.error.path=/error
spring.session.jdbc.initialize-schema=always

# Secrets (you can't have them)
spring.config.import=optional:file:secrets.properties